index:
    path: /
    controller: App\Controller\DefaultController::index
post_index:
    path: /post/{id}
    controller: App\Controller\PostController::index
    requirements:
        id: '\d+'
category_index:
    path: /category/{id}
    controller: App\Controller\CategoryController::index
    requirements:
        id: '\d+'